### ISSUE TITLE
As a user, I expect the Contact's Home Phone to stay syncronized with the Household Account's Home Phone.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1033]
Hub thread: https://powerofus.force.com/0D58000001SJCBW

**Comment by davidhabib** [comment]
more comments from the Hub:

Mark Westwind (EarthTeam)
As a user, I would like NPSP to link the HH Account Phone to the Contact Home Phone instead of a separate Household Phone formula field. This would bring the HH Phone into the purview of the Preferred Phone functionality. Otherwise, there's a risk that the Phone field may end up empty if the HH Phone is not copied to the Home Phone field. This also complicates reporting - by design, the Preferred Phone is supposed to be the only phone field needed in reports. I grant that there may be HHs where the primary HH phone is different from a Contact's "preferred home phone" ... but I can't imagine that it's common enough to require two fields as the default. I also understand that the current HH Phone formula field is an easier implementation, but unless I'm missing something, it sure would be great to see this change in a future revision.

**Comment by kbromer** [comment]
**lurch: attach W-007336

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZKAAY" target="_blank">W-007336</a>

**Comment by Jeffissenberg** [comment]
Is this item being worked on?

**Comment by judisohn** [comment]
@Jeffissenberg No, not yet.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
