### ISSUE TITLE
Any change to Recurring Donation with Open-ended status of 'None' causes donations to be deleted and re-inserted

### ISSUE THREAD

**Issue by Filikin** [SalesforceFoundation/NPSP#1386]
Based on NPSP documentation, I would expect that when a Recurring Donation Close Date or Amount is updated, all related donations are deleted and recreated.   However, I am now seeing this deletion and recreation happen when I make any change in the recurring donation.  In the process, any user-defined data set at the Opportunity level is being lost.    

This may be related to https://github.com/SalesforceFoundation/Cumulus/issues/1359 
The behaviour has only been reported this week, so may be related to Spring 15.

**Comment by davidhabib** [comment]
This has been the behavior since I reworked parts of recurring donations back in early 2014.  The logic used to incorrectly refresh non open-ended rd's, so I changed the logic to always delete any open opps on the rd, and then go through the same logic for creating a new rd's opps.

This gains consistency and reduced some complication in the code (though not all!).  Unfortunately, it does have the side effect that any changes the user manually did to any of the open opps will get lost.  I'm not sure if it is worth trying to rearchitect this complex code for this scenario.

**Comment by kbromer** [comment]
**lurch: attach W-007250

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXwAAI" target="_blank">W-007250</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.123 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.123

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000A8Lg2AAF" target="_blank">W-023466</a>

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
