### ISSUE TITLE
As an admin or contributor, I'd like the fields related to Account Model to be cleaned up so I can understand things better 

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1465]
and am not afraid of breaking things by mistake.

**My comments are after the arrow (==>).**
- Account - SYSTEM_AccountType__c (text) Description: “Indicates which model drives Contact relationship behavior: Individual (Bucket) or One-to-One”  ==> What about Household Account Model? Does the description need to be updated?
- Account - SYSTEMIsIndividual__c (checkbox) Description: “Indicates whether or not this Account is an Individual (true) or Organization (false).” ==> This is NOT referring to the sometimes called Individual account model, aka Bucket, correct? Individual here means person, unlike in the field description above, right?
- Account - One2OneContact__c (lookup) ==> No description. I think it’s the related contact, if the One-to-One model is being used for that contact. Null otherwise.
- Contact - HHId__c (formula: if(Account.SYSTEM_AccountType__c=='Household Account',CASESAFEID(AccountId),null)) Description: “holds the ID of the current Household Account.” ==> Description should also say: “if using Household Account model.”
- Contact - Organization_Type__c (formula: NULLVALUE(IF( Account.SYSTEM_AccountType__c=="", TEXT(Account.Type),Account.SYSTEM_AccountType__c),"Organization" )) Description: “In order of preference, the SYSTEM_AccountType field, the Account Type field, and "Organization".” ==> Is this field really necessary? It’s just used in ACCT_IndividualAccounts_TDTM in a few places. It feels like we should be able to get the information we need from the parent account.
- Contact - Primary_Affiliation__c (Lookup to Account) Description: “Used to track the account of the contact's Organization Affiliation record that is marked primary.”
- Contact - Primary_Contact__c (Formula: Account.One2OneContact__c = Id) “Automatically checked if the Contact is the Primary Contact on their Account.” ==> Not used?
- Contact - Type_of_Account__c (Formula: IF(Account.SYSTEMIsIndividual__c,"Individual","Organization")) Description: “"Individual" or "Organization" depending on Account setting.” ==> Not used?
- Contacts_And_Orgs_Settings__c - Account_Processor__c (text) Description: “Setting for the Account model. Should be "One-to-one" or "Individual". Replaces the custom field Contact.SystemAccountProcessor__c” ==> Should the description also include “Household Account” as one of the possible values?
- Contacts_And_Orgs_Settings__c - HH_Account_RecordTypeID__c (text) ==> I think it could be deprecated
- Contacts_And_Orgs_Settings__c - One_to_One_RecordTypeID__c (text) Description: “The ID of the record type to be used for 1x1 accounts. If none is selected, the account will default to the user's default account selection.” ==> I think it could be deprecated

**Comment by judisohn** [comment]
"Account - One2OneContact__c (lookup) ==> No description. I think it’s the related contact, if the One-to-One model is being used for that contact. Null otherwise."

Its label is now Primary Contact, and if using Household Account model it's just that. What about as help/description something along the lines of: This is the related Contact if using One to One model. The Primary Contact if using Household Account model. It should be blank for Individual Bucket model.

"Contact - Organization_Type__c" - I believe this was done because Record Types weren't used prior to NPSP 3 and the AccountType would be blank if not Household. Given that, I've always wanted the Account.AccountType field to be labeled as Individual Account Model which is more telling what it is/what it means.

"Contact - Primary_Contact__c (Formula: Account.One2OneContact__c = Id) “Automatically checked if the Contact is the Primary Contact on their Account.” ==> Not used?" Yes, it's used - it's helpful in Contact reports to filter and show primary contacts only. Helps to not have to use the Household deduplication functionality on campaign to be sure you're adding just one contact from a household to a campaign, for example.

**Comment by kbromer** [comment]
**lurch: attach W-007442

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cbnAAA" target="_blank">W-007442</a>
