### ISSUE TITLE
Feature Request: Update Additional Fields Upon Contact Marked Deceased

### ISSUE THREAD

**Issue by bmcguirk** [SalesforceFoundation/NPSP#1738]
Hi there - 

Expanding upon the (fantastic, much-welcomed) functionality developed in #1328 , it would be nice to be able to update additional fields (we have a "Do Not Mail" field, specifically, as some of our younger members have specified that they want email-only communication, for example. Flagging the contact as "Do Not Contact", "Do Not Email", "Do Not Call" but not "Do Not Mail" is a little odd) when this is triggered. Perhaps exposing this via the NPSP Settings tab or the regular workflow rule settings might be an option? That's for you guys to decide, of course. 
Thanks.

**Comment by judisohn** [comment]
Thanks @bmcguirk - sounds like the real request here is that additional 'Do not Mail' field. I agree that a 'Postal Opt Out' field is needed, for sure. I always thought that made the most sense on the Account, rather than the contact. Do you agree? Because most orgs I've seen send postal mail to the entire household, and if one person opts out that should mean that nothing should go to that house. What do you think?

**Comment by bmcguirk** [comment]
@judisohn Agreed. Unfortunately, I think most orgs send duplicates because of non-householded data, but Household/Account level would be the proper level. 

My specific request is, you're right, to be able to flip "Do Not Mail"/Postal Opt Out. I just thought I could imagine other actions organizations might want to link to this trigger (acknowledgments, tasks, etc.)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwhAAA" target="_blank">W-008331</a>

**Comment by davidhabib** [comment]
Karen Fitton asks for us to also remove the contact from being the household's primary contact.  https://powerofus.force.com/0D58000002K4bfk
