### ISSUE TITLE
The NPSP Has a lot of English Language that should be Custom Labels

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1775]
With Richard Saunders and Russ Feldman, we completed a full inventory of the NPSP visualforce hard-coded english strings. These should be (and will be) replaced with Custom Labels by @cdcarter.

A document of all known english language strings is found here: https://docs.google.com/spreadsheets/d/1Ba_EM-0FPY_2QARn8IymNGbGGZEys3XpSGGgA-UjJ-E/

**Comment by kbromer** [comment]
This brings up an interesting question. I intentionally didn't make the strings in the converter translatable as custom labels because, in theory, it was a one-time-use page (hopefully!) and wouldn't need regular usage, so I couldn't imagine a scenario that Google Translate wouldn't solve - especially given that once you create those labels, they're there for the life of the package.  I'm totally open to label-ifying it though, just thought it might be worth sharing the context :)

**Comment by cdcarter** [comment]
Some context from why we started this: Mary Pustejovsky is working on lining up translators (sounds like we already have ES and FR volunteers ready).

I hear the concern about putting the labels into the package, but at the same time, the page is stuck in the package too. Even if there are *few* orgs that are currently on 2.0 in another language, and that group will theoretically only get smaller -- it seems like this is the kind of page that NEEDS an accurate and considerate translation. Already there's a lot of fear and confusion about the docs here, and there's no way that's easier through google translate ;)

That said, I'll be pushing my commits one page at a time. There are a lot of pages that have everything in labels except one or two small things, which I think *aren't* intended to be that way. I leave it up to product team to determine if the tradeoff is worth it on a page by page basis.

**Comment by mbeaty-sf** [comment]
W-9305423

**Comment by mbeaty-sf** [comment]
This issue has been addressed in subsequent releases.
