### ISSUE TITLE
Add custom Organization address fields for the affiliated company

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1801]
hub request here: https://powerofus.force.com/0D58000002MvTwT

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gy8AAA" target="_blank">W-008636</a>

**Comment by cdcarter** [comment]
On the lead convert page, we offer the user the opportunity to convert the lead into a household/individual/bucket account or into a company account. 

This issue requires adding a set of "CompanyAddress" fields onto Lead, so that when converting a lead and creating a household, we can populate both the HH address as well as the affiliated account address.

So...here's the question -- when the user opts to convert the lead into a company account, should the company account address be populated with with standard Address field on Lead (current totally normal behavior), or with the new "CompanyAddress" fields?

**Comment by davidhabib** [comment]
I'd go with if the company address fields are filled in, use them, otherwise use the standard address fields.
@judisohn thoughts?

**Comment by judisohn** [comment]
I agree with @davidhabib 

Now question for you @cdcarter - what happens if they have Standard and Company Address filled in with different data? Are you also going to have an option on the lead for them to indicate which should be the primary for that Lead and therefore the Contact's 'Current Address' on conversion?

**Comment by cdcarter** [comment]
These are great questions!

In one world Lead.Address could map to Account.BillingAddress and Lead.CompanyAddress could map to Account.ShippingAddress. This would be a bit "principle of least surprise"-y, since Lead.Address would end up in the same place no matter what. Then, one would continue to expect that the Contact's current address maps to Lead.Address.

Perhaps instead of Lead.CompanyAddress it should be Lead.SecondaryAddress, which maps to Accoutn.ShippingAddress.

[Again, this is all in the context of when creating an org account instead of a HH account on lead conversion. When creating a HH plus an affiliated org, the behavior is cut and dry]

**Comment by judisohn** [comment]
I'm not entirely thrilled with mapping anything to Account.ShippingAddress. We don't have any code/functionality around the Shipping Address fields and my fear is there would be an assumption that an Address record would be created in that scenario and there wouldn't be. And it makes for some pretty challenging reporting.

**Comment by cdcarter** [comment]
I hear that.

What behavior would you imagine if you filled out both Lead.Address and Lead.CompanyAddress and converted to an org acct?

**Comment by judisohn** [comment]
it's more a question of what is on the Contact, since it's clear what would be on the Account (for the Company record, whether it's the Contact's primary account or through affiliation). I'm still leaning towards one more custom field on Lead for 'Set as Contact Mailing Address' with a picklist. Or a checkbox for 'Set Company Address as Contact Mailing Address'. Then it's clear what intention is.

**Comment by cdcarter** [comment]
I'll stub out another picklist and then maybe finally add some action to that vfp to only display the relevant sections.

**Comment by davidhabib** [comment]
Uhg.  I'm not happy with all these custom fields and choices being added to leads and the converter page.  I think this is really making things way more complex than they need to be.  So let me try a simpler proposal.  Currently Leads have just one set of Address fields.  We add a set of Company Address fields.

when they convert to a household account and an affiliated company we do:
Contact - gets lead Address fields
Household Account - gets lead Address fields
Affiliated Company - get lead Company Address fields

when they convert to a Company instead of household account:
Contact - gets lead Address fields
Org Account - gets lead Company Address fields if they are not empty.  If empty, use lead Address fields.

This seems simpler to me then adding additional choices and checkboxes, and seems to be reasonable.  thoughts?

**Comment by cdcarter** [comment]
I find that reasonable, and is indeed the current behavior in my PR.

**Comment by gfuller30** [comment]
Sorry, for the late chiming in on this.  I think I am favoring David's approach.  I was about to submit my idea to Christian on git, but perhaps I should do it here:  Let me know what you think:
Currently if a lead comes in from a school or foundation, and we want to convert that lead (including creation of a new opportunity), there is no way to specify the opportunity be attributed to the affiliated organization.  I think your specific solution for addressing this would work very well for us.

Similarly, the way lead conversion handles conversion of the affiliated organization falls short in that none of the business address information or organizational information included with the lead converts to the affiliated organizational account.

My suggestion is to have a set of secondary address fields added to the lead object.  Like the contact object, the various set of address fields can be defined with an address type, (npe01__Primary_Address_Type__c and npe01__Secondary_Address_Type__c).    I think this would enable the following on lead conversion:

•	If the lead getting converted includes the conversion of a NEW affiliated account, the conversion would:
o	Grab the addresses from the field set that is of the ‘Work’ type and populate the Billing Address fields of the Affiliated Organization record related to the contact being converted.
o	If a work phone number and/or fax number exists in the lead, this would get converted to the Phone and Fax number fields of the Affiliated Organization record related to the contact being converted
o	All fields related to organizations would also get populated to the affiliated organization record related to the contact being converted.  This includes the following fields:
	Industry
	Lead Source
	Fax
•	If the lead getting converted is being merged into an existing affiliated account, nothing would get populated to the existing affiliated account.  This is to ensure that a representative of the organization working at a different address than the primary address of the organization does not overwrite the Billing Address fields of the affiliated account
•	While this might be outside the scope of the update we have been discussing, it might be a good idea to have some way of managing addresses between Affiliated Organization Accounts and their linked contacts defined in the npsp__Primary_Affiliation__c of the contact record.  I am suggesting something similar to how address management used to work between contacts and their Households (the npo02__Household__c object).  I suggest the following functionality:
o	A button on the contact record to copy the Work Address fields from the Contact record to the related Primary Affiliated Organization’s Billing Address fields.
o	A button on the Organization Account record type that would copy the Billing Address from the affiliated Organization to all related contacts listed as CURRENT affiliated contacts. 

I think the above set of buttons is probably necessary because I don’t think you would want the kind of syncing that exists between Household Accounts and their Contacts since employees of organizations might work at different addresses from the address of the Organization.

Anyway, these are my thoughts.  Thanks for letting me share them with you.  I’m looking forward to seeing what you and your team come up with regarding this.

**Comment by mbeaty-sf** [comment]
This functionality exists in NPSP, upon lead convert the Company Address fields carry over to the Primary Affiliation of the created Contact.

NPSP Lead Conversion - https://powerofus.force.com/s/article/NPSP-Convert-a-Lead-to-a-Contact
