### ISSUE TITLE
Affiliations connect to addresses

### ISSUE THREAD

**Issue by stevebackman** [SalesforceFoundation/NPSP#2002]
Connect Affiliations to Account Addresses for that org.  Sprint issue.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003VoZBAA0" target="_blank">W-009983</a>

**Comment by mpusto** [comment]
@stevebackman and @judisohn Could you provide more detail around this? I am not sure I follow and more detail will help us prioritize in the backlog.

**Comment by judisohn** [comment]
@stevebackman please let me know if this wasn't the issue - but here's what I've heard on this one:

If a user selects the Primary Address Type on a Contact to be Work, and there's no Address record connected to their Household that is type = Work, but they do have a Primary Affiliation with an Address (either as a default Address or data in the Billing fields) then that should be the Contact's Mailing Address. Otherwise, the organization has to create a duplicate Address record on the Household for that's Contact's work address.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
