### ISSUE TITLE
System.LimitException: npsp:Too many DML statements: 151

### ISSUE THREAD

**Issue by TannerWells-IdealistConsulting** [SalesforceFoundation/NPSP#2095]
This issue has occurred on occasion (just in the past month) when the iATS Brickwork application completes DML inserts/updates  (~8 DML statements and 20 DML rows). I reviewed the debug log and most of the DML statements from the NPSP are 'savepoints'. There are entries up to 'SavepointValue114' and beyond. There are only a few insert/update statements though from the NPSP. I'm happy to send you the debug log to help investigate this further as I'm not sure what could be causing the issue. 

Thanks!

**Comment by davidhabib** [comment]
Tanner, can you provide more details.  What are you specifically inserting and updating in one transaction?

**Comment by TannerWells-IdealistConsulting** [comment]
iATS Transaction, iATS Customer Code, Contact and Opportunity records. Would you like me to send you the debug log?

**Comment by judisohn** [comment]
@TannerWells-IdealistConsulting have you opened a ticket with iATS support on this? While you're seeing the error at savepoints in NPSP code, they may have advice on the proper way to insert records to avoid these errors in their custom objects.

**Comment by TannerWells-IdealistConsulting** [comment]
Hi Judy, thanks for the suggestion but I'm the lead developer on the Brickwork application. I've reviewed the NPSP code and haven't been able to determine why there is a large number of savepoints being created.

**Comment by davidhabib** [comment]
whenever any of our triggers run, you can see in https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/TDTM_TriggerHandler.cls#L76 that we first call setSavepoint, so we can roll back then entire transaction if the trigger fails, and then optionally record the error in our Error Log and/or send emails.  Without using setSavepoint, we have no ability to log error messages, since the implicit rollback an exception coming from our trigger to salesforce will cause all DML to get rolled back.

**Comment by TannerWells-IdealistConsulting** [comment]
Thanks David. Do you have any idea why the trigger is running so many times or how we can reduce it to avoid the DML limit due to the setSavepoint?

**Comment by TannerWells-IdealistConsulting** [comment]
Thanks. It's a single DML call (insert) for each list (not for each record). There are also single update calls for contact, payments, opps, and iATS Transaction update lists. Let me know what other information I can provide. I'll send the debug log shortly.

**Comment by TannerWells-IdealistConsulting** [comment]
Hi David, I just sent you the debug log via email.

**Comment by davidhabib** [comment]
As I feared, the debug log is relatively worthless given that it is covering a very large scenario, so Salesforce is truncating much detail out of the log, and the fact that it treats our managed package as opaque, so we don't get any insight into what our code is doing or any of our debug output.

What would be most helpful would be for you to write down exactly what your scenario is in step by step format.  for example:

- insert 10 iATS Foo records
- iATS trigger on Foo object will then create 10 Contacts
- NPSP creates Contacts and their Household Account
- iATS trigger on Foo object then creates 10 opps (1 for each contact)
- NPSP creates the OpportunityContactRoles 

then we can get a better idea of what you are doing within a single transaction and where the issue might be.  also please note which account model you are using, what workflow rules you have activated on the affected objects.

**Comment by TannerWells-IdealistConsulting** [comment]
Thanks for the quick response. Here is the scenario:

-Callout is completed to iATS web service to obtain iATS Transactions and iATS Customer Codes
-Batch DML then begins
-checks to see if a contact duplicate exists. Duplicates are updated, new contact records are inserted.
-Opportunity records are inserted
-NPSP creates the OpportunityContactRoles (iATS sets the 'npe01__Contact_Id_for_Role__c' field)
-iATS Customer Code records are inserted
-iATS Transaction records are inserted
-IATS_transaction_Rollup_tgr runs which updates cumulative fields on the iATS Customer Code and Opportunity objects. 

Account models for client's affected: Both are on the 'One-to-One' account model.

**Comment by davidhabib** [comment]
1. so in a single batch, how many contacts would you Update or Insert?  
2. I assume that would be with a update listOfContacts or insert listOfContacts, rather than a separate update or insert call for each contact.
3. how many Opportunities inserted in a single batch?  with one insert call or multiple?
4. how many iATS Customer Code and Transaction records inserted? 
5. for each iATS Transaction record, does the trigger update 1 Opp, or can there be multiple opps per transaction record?  
6. are the Opp updates done with a single update call, or multiple?

**Comment by TannerWells-IdealistConsulting** [comment]
1. so in a single batch, how many contacts would you Update or Insert?
maximum is 1000

2. I assume that would be with a update listOfContacts or insert listOfContacts, rather than a separate update or insert call for each contact.
Yes, they are all list updates. All DML is bulkified._ 

3. how many Opportunities inserted in a single batch? with one insert call or multiple?
maximum is 1000 via one list insert call. 

4. how many iATS Customer Code and Transaction records inserted?
maximum of 1000 iATS Customer Code Records and 1000 iATS Transaction records. 

5. for each iATS Transaction record, does the trigger update 1 Opp, or can there be multiple opps per transaction record?
One transaction record only updates a maximum of 1 opp. The code determines the opportunity (related to the triggering iATS Transaction) and then all iATS Transactions related to that opportunity. It then calculates the Totals and updates the opportunity records. This is all bulkified. 

6. are the Opp updates done with a single update call, or multiple?
single update call to list. Customer Code list is update and then Opportunity list is updated. 

We have one other client that is affected (3 total) who is also on the 'One-to-One' model. 

Thanks!

**Comment by davidhabib** [comment]
So I first reviewed this great article to refresh my memory on various limits, transactions, and packages: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apexgov.htm

important points:

- no matter the DML list size, triggers are called with a max of 200 objects.  So if you do a single insert of 1000 contacts, the contact insert trigger gets called 5 times, and each invocation gets its own set of transaction limits.

- certified managed packages get their own transaction limits.  So in a user's org, if they have a contact trigger, and NPSP has a contact trigger, and iATS has a contact trigger, each gets its own 150 DML statements (assuming iATS is certified).  there are a few caveats, like total cpu time isn't split across each namespace, but DML is separate for each.

- inserting or updating contacts into NPSP is a non-trivial process, due to all the work we must do to create an account (household or one-to-one), potential address management (create address object, propagate address to account and other household members), affiliation management (auto-create if primary affiliation set).  I'm sure there is other logic I'm forgetting as well.  When customers do data loading into NPSP, they typically must lower their batch size to < 100, to successfully insert contacts and their related objects.

- when an Opportunity is created or updated, we also have a fair bit of work to do.  We have auto-naming logic to apply, we have to create or update payments, we have to recalculate payment rollups, and we have to update donor rollups on the primary contact.  I'm not sure if people have to reduce batch to < 200 or not with Opps, but something to keep in mind.

- given the above known limitations, I encourage you to lower you batch sizes so you are not inserting or updating such large quantities of Contact and Opps at one time.

- finally, there are some very good limits api calls you can put in your code to print debug statements tracking limits, to help identify places where your limit usage is going too high.

I hope that info helps, and allows you to get iATS working successfully within the current limitations that the system enforces on all our code.  Let me know how it goes.  thanks.

**Comment by davidhabib** [comment]
@kbromer @njjc @dospromptman fyi, see my previous post on this issue.

**Comment by TannerWells-IdealistConsulting** [comment]
Thanks you for the detailed response! I've been reviewing this further as the error is still occurring for DML inserts as low as 7 records. This issue is now just affecting one of our clients. There is a custom trigger on the client's opportunity object which may be part of the issue. I'm reviewing the logic and related log. In the meantime, can you envision any reason this would occur with such a low batch size (7 records)? Thanks again for all your help!

**Comment by davidhabib** [comment]
in a default NPSP org, certainly a batch of just 7 is not a problem.  So i can only guess there is some interaction between the customer's trigger, which is causing additional DML, and thus causing more code to run.

**Comment by mbeaty-sf** [comment]
Given that there has been no subsequent activity on this Issue for the past 5 years, we are going to assume this is no longer occurring.
