### ISSUE TITLE
Account Converter: Populate Legacy 1:1 Account ID on Contact

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2484]
Anne Crawford made this suggestion as we've been working on the conversion workbook. 

We currently have an option to populate the legacy Household ID on the Account. It would be helpful for post-conversion data clean up and manual migrations to have a similar option for the legacy 1:1 Account ID on to the Contact record.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004v1biAAA" target="_blank">W-017704</a>

**Comment by kbromer** [comment]
I'm confused as to why you'd need this - wouldn't any legacy or missed conversions still be attached to an Account with the 1x1 record type id?

**Comment by judisohn** [comment]
Not all conversions had record types on those accounts before NPSP 3. Most didn't, from what I saw (have to rely on the _SYSTEM:AccountType field instead). In a perfect world, you're absolutely right. But as Anne and I have been talking it appears that every conversion requires significant clean up and comparison of data afterwards and the ID would be helpful in that respect.

**Comment by annecrawford** [comment]
The most common reason this is needed is to reparent opportunities that are stranded on their old one-to-one account.  This usually happens because the OCR was not marked primary, is duplicated or is missing.  Or the one-to-one account was misconfigured -- what I often see is that the Primary Contact's account is different than the One-to-One account (duplicate contacts.) Most of these should be identified in pre-conversion testing.  And if it's just a few it's easy enough to manually reparent the opportunities.  But if there are a lot, it's a pain to have to go to the backups and do VLOOKUP.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
