### ISSUE TITLE
Reducing RD Opp Forecast Months fails if too many Opps would be deleted

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/NPSP#2515]
Hub thread: https://powerofus.force.com/0D58000003GGmub

If you try to set the Opp Forecast Months to a value such that > 50k Opportunities should be deleted, you will get a "Too many query rows" error. 

The ```STG_PanelRD_CTRL.trimOpportunities()``` method has no LIMIT or ability to work as a batch job.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005KmT0AAK" target="_blank">W-017964</a>

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
