### ISSUE TITLE
auto refresh opportunity name on appropriate updates to opportunity

### ISSUE THREAD

**Issue by benderguy** [SalesforceFoundation/NPSP#2539]
A recent (and some past) client has requested that their opportunity renaming be fully automatic, so that the naming formulas are fully enforced and the names are always updated. This would seem to work well if I could get the class OPP_OpportunityNaming to execute upon update of the opp record. However, it doesn't appear that this class is TDTM enabled. Can we make it so? Is there a better way?

**Comment by davidhabib** [comment]
the solution is a new trigger handler that detects the appropriate field updates to opportunity that would change the opportunity name, and call refreshOppNames() on that opp.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005Zq2DAAS" target="_blank">W-018174</a>

**Comment by mpaquinfionta** [comment]
Is this still on the roadmap. One of our client would benefit from calling OPP_OpportunityNaming from a trigger.

**Comment by coriobriensfdo** [comment]
@mpaquinfionta this Issue is still open therefore being considered for future development, though not necessarily on the in-development roadmap.

We use the Power of Us Hub for conversations related to future development however, and try keep GitHub for lodging of actual bugs. I'd recommend posting in the Power of Us [Hub](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack), and specifying your particular use case.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
