### ISSUE TITLE
Change Recurring Donation payment limit error to look for specific Status, not absence of Open

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2755]
[Thread.](https://powerofus.force.com/0D58000003eM1cA)

First, we should investigate and clean up the error: "You must specify fewer than 50 installments. (This error message is no longer used)." (clearly, it is)

Happens [when](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RD_RecurringDonations_TDTM.cls#L90) the Open Ended Status is specifically not Open or Closed. Consider adding label for fixed length rather than assume any non-Open/Closed Status to allow for maximum customer flexibility when working with the object.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008FKD6AAO" target="_blank">W-020505</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.

**Comment by jamesmelville** [comment]
Hi @judisohn @mbeaty-sf @force2b, can I ask why this won't be explored further?

With impeccable timing (and as per my post https://powerofus.force.com/s/feed/0D58000003eM1cA), we've just hit the limit of 100 donations, and so I've just upped it to 150 with my fingers crossed that it doesn't break anything else. Whilst it's great to be reminded how we have such long term donors, in a few years time I'd like not to have to carry out the same archaeological process I have this evening, googling and finding my own posts reminds me that my memory is not as great as I like to think. I'd have posted this in the hub but it seems things are on the move.

Googling around, I can see that some new "Enhanced Recurring Donation" functionality has dropped which I should probably look to migrate to - it looks like I might be able to import donations each month, and the system will simply forecast out the next donation and move it along as appropriate to my imported donation, so maybe I can move my "Open - Manual" donations back to simply being "Open". 

But the docs do say that the legacy functionality is still supported, so I wonder if there's an argument that:
- I should be able to create more donations than the limit where the RD is of record type "Open Ended" but not of open ended type "Open" or "Closed"
- this error message should be fixed (it's still in use despite its claims)
- the error should reflect the max donations configured in the org rather than the hard coded 50

**Comment by judisohn** [comment]
@jamesmelville The legacy recurring donation system is supported as it currently is and no further. Improvements and closing of gaps in functionality are only in Enhanced Recurring Donations, which does not schedule future Opportunities in the same way.

Learn more here: https://powerofus.force.com/s/article/NPSP-Recurring-Donations-Overview-and-Setup
