### ISSUE TITLE
Recurring Donation changed from Open to Closed and back to Open does not refresh forecast opportunities

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2759]
If an administrator Closes an Open Recurring Donation and then changes it back to Open (either by mistake or because donor changed their mind), the forecast Opportunities are not updated back to where they should be. They remain Closed Lost or deleted. Refreshing Opportunities or running batch does not restore them.

**Comment by judisohn** [comment]
*lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008LN4FAAW" target="_blank">W-020539</a>

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
