### ISSUE TITLE
If Primary Contact in Household is updated to blank value, and Contact remains in Household, Primary Contact stays blank

### ISSUE THREAD

**Issue by MustafaJhabuawala** [SalesforceFoundation/NPSP#2816]
I am facing an issue while removing the Primary Contact from Household. As I remove the Primary contact from Household it should set some default Contact as primary contact and create new household for removed contact. This functionality works fine for first 3 to 4 records but after that the functionality is not working as expected i.e when I remove the Primary contact from household it does not remove the member from household and it the Primary Contact is set to blank.

**Scenario -** 

**Steps 1** - Account - A1 Household

**Step 2** - **A1 Household Members** - C1(Primary Contact), C2, C3

**Step 3** - Click on **Manage Household** button from Account record

**Step 4** -  Remove Primary Contact **C1** from the household

**Expected** - C1 has to be removed from current household and a new household has to be created and set any random contact as a Primary Contact for current household.

**Actual Result** - C1 is not removed from the current household and Primary Contact of current household is set to blank

****Note** - I have tried this in multiple sanboxes and the same issue is occurred.**

**Comment by judisohn** [comment]
Hi @MJ0052 In the future, please post in the [NPSP Group in the Power of Us Hub](https://powerofus.force.com/0F980000000CjRe) when you suspect an issue. 

If when on the Manage Household page, you remove the value in the Primary Contact lookup field at the bottom *and* click the 'x' to remove the Contact from the Household, a new member is selected as the Primary Contact. It appears that you only removed the Contact from the Household, but did not change the lookup to the Primary Contact. 

I'm adding this to the backlog with an updated title to address the scenarios where the Primary Contact could be blank which is definitely not desirable. 

Replicated in scratch org. You must both remove the Contact from the Household and set Primary Contact to null to avoid having a Household without a Primary Contact. We should update the Primary Contact to its prior value when set to null (forcing user to remove the Contact from the Account first in order to have another Contact auto-selected). The Primary Contact in a Household should not remain blank.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SVORAA4" target="_blank">W-020996</a>

**Comment by MJ0052** [comment]
Hi @judisohn 

Thank you for the quick response.

As per your comments, I want to re-phrase the statement. Below are the details -

**Step 1 -** A Household has four (4) members - Q1(Primary Contact), Q2, Q3, Q4

![image](https://user-images.githubusercontent.com/9639440/31985092-82c42574-b981-11e7-9f7b-3c2e8e31b8fa.png)

**Step 2 -** Click on Manage Household button - As per your instructions, I have removed **Q1** from household by clicking on 'x'
**Note -** If you are removing the contact by Clicking on 'x' which is a primary contact, then the Primary Contact look up which is displayed at the bottom of Manage Household Page sets to blank.

![image](https://user-images.githubusercontent.com/9639440/31985393-96fe433e-b982-11e7-9921-c9d901d987ac.png)

![image](https://user-images.githubusercontent.com/9639440/31985167-c7c63bb2-b981-11e7-8af7-d8b9390de4ea.png)

**Step 3 -** Selected **Q2** as a **Primary Contact** from the look up in Manage Household screen itself and Click on Save button

![image](https://user-images.githubusercontent.com/9639440/31985250-1a26e4ec-b982-11e7-8229-3d7e0a3b84fb.png)

**Step 4 -** Click on Save

![image](https://user-images.githubusercontent.com/9639440/31985449-c91b579e-b982-11e7-81c9-4e41007893a7.png)


**Expected Result -** **Q1** contact has to be removed from household as I have clicked on 'x' from Manage Household screen and the Primary Contact has to be populated as **Q2** for the household.

**Actual Result -** **Q2** is selected as the new Primary Contact (which works as expected) but the **Q1** stays in the same household (issue)

![image](https://user-images.githubusercontent.com/9639440/31985583-3a87a93c-b983-11e7-9651-3e09770cb4a7.png)


**Note -** I have attached screen shot for more details.

**Comment by coriobriensfdo** [comment]
[Another Thread.](https://powerofus.force.com/s/question/0D51E00004vaphLSAQ/odd-behavior-when-trying-to-split-household)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
