### ISSUE TITLE
Currency on Recurring Donation is not in sync with currency on related Opportunities

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3043]
Hub thread: https://powerofus.force.com/0D580000048d7HB

Confirmed in a scratch org - changing currency on parent recurring donation record from the corporate default does not change currency on open opportunities. Update does not fire in 'Refresh Opportunities' or scheduled job.

**Comment by judisohn** [comment]
Linked to [W-024076](https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x8000000AVZ8EAAX/view)

**Comment by coriobriensfdo** [comment]
[Another Hub Thread.](https://powerofus.force.com/s/question/0D51E000051ow06SAA/not-mapping-currencyisocode-in-opportunities-when-recurring-donation-are-modified-any-ideas)

**Comment by coriobriensfdo** [comment]
Additional Details:

**Steps to Reproduce:**

1. Enable Multicurrency in an org. Add a second currency, such as CAD so that you know have two currencies (say USD and CAD).

2. Create a new Recurring Donation. Field don't matter with the exception of: 
- Select CAD as the Currency value
- Amount: $1000
<img width="902" alt="Screen Shot 2019-09-25 at 4 27 29 PM" src="https://user-images.githubusercontent.com/37851761/65711740-68163b80-e04a-11e9-9b28-7f814c930924.png">

3. Note that the new child Donations are setup correctly as $1000 CAD and shows USD conversion. 
<img width="1362" alt="Screen Shot 2019-09-25 at 4 27 16 PM" src="https://user-images.githubusercontent.com/37851761/65711765-7b290b80-e04a-11e9-848e-4c1755f0bf34.png">

4. Modify the Recurring Donation record to reflect USD currency and a new amount (say $5000) and save. 
<img width="471" alt="Screen Shot 2019-09-25 at 4 28 40 PM" src="https://user-images.githubusercontent.com/37851761/65711927-cd6a2c80-e04a-11e9-869d-998544c600de.png">

5. **Expected Result:** The child Opty donations (that are not in a Closed stage) will be recreated to reflect the updated Amount and Currency values.

**Actual Result:** The child Opty donations (that are not in a Closed stage) are recreated with the updated Amount value ($5000), but the Currency value remains the original value (in this case USD), which incorrectly reflects the USD currency conversion.
<img width="465" alt="Screen Shot 2019-09-25 at 4 29 16 PM" src="https://user-images.githubusercontent.com/37851761/65712306-99dbd200-e04b-11e9-8fcc-9bbcd4616f99.png">

<img width="1376" alt="Screen Shot 2019-09-25 at 4 28 58 PM" src="https://user-images.githubusercontent.com/37851761/65712315-9ea08600-e04b-11e9-968c-c5bf446d97b7.png">

**Workaround:** Create a workflow or Process Builder to update the Child Opty Currency value with the value from the parent Recurring Donation.
