### ISSUE TITLE
Improved UI for creating and editing recurring donations

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#305]
_Issue by **[greenstork](https://github.com/greenstork)** from Monday Nov 12, 2012 at 17:55 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Recurring_Donations/issues/23_

---

I think creating a new recurring donation is screaming out for some custom UI and this field, while it could be incorporated into that UI, would be the first on the chopping block to save to actual schema.  At the very least, some help text for this field would be great.

**Comment by davidhabib** [comment]
**lurch: attach W-007214

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cVfAAI" target="_blank">W-007214</a>

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
