### ISSUE TITLE
If Opportunity Primary Contact role is updated from null, existing Contact Role records are deleted

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3805]
CRLPs do not need to be enabled to replicate.

Steps to repeat:

1. Create Organization Account. Create 2 Contacts.
2. Create Opportunity. Associate to Organization Account, leave Primary Contact blank.
3. Create Opportunity Contact Role record for one of the Contact records. It does not matter the role or whether or not Primary is checked on the OCR. For this example, assume the intention is that this contact is to receive soft credit with a role of 'Influencer.'
4. Update Opportunity to populate the Primary Contact field connected to the other Contact.

Expected behavior: The now Primary Contact should receive an OCR checked as Primary using the Organization role set in NPSP Settings. The existing Contact Role should remain for the 1st contact with the role as defined.

Actual behavior: Existing Contact Role records are deleted, leaving only the now Primary OCR.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPY9QAM" target="_blank">W-029765</a>

**Comment by coriobriensfdo** [comment]
Partner reported the OCR's are being removed even if the Primary Contact field is not blank, which I can repeat.

To Repro:

If you have an Opp with a Primary Contact of Contact X and the following contact roles
-	Contact X (Primary contact role)
-	Contact Y (Influencer)

If you change the Primacy Contact to Contact A, it will redo the roles so you will end up with:
-	Contact A (Primary contact role)

**NOTE: If you change the Primary Contact from X to Y (rather than A as in this example), the roles are modified properly.

**Comment by jesslopez-sf** [comment]
Workaround: check off the DisableContactRoleAutomation__c field on the Opportunity prior to adding/changing the Primary Contact field.
