### ISSUE TITLE
FIELD_INTEGRITY_EXCEPTION when adding field whose API name exceeds 38 characters to Relationship Sync Excluded Fields

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/NPSP#4052]
If a user adds a field in NPSP Settings > Relationships > Relationships > Fields to Exclude from Sync that has an API name longer than the 38 characters allowed for the Name of a List Custom Setting record, they get an error, eg: 

> Error: Insert failed. First exception on row 0; first error: FIELD_INTEGRITY_EXCEPTION, Custom Setting Name too long: npsp__related_opportunity_contact_role__c: [Name]

[Hub link](https://powerofus.force.com/0D51E00004gJZIs). NPSP now ships with a field, `npsp__related_opportunity_contact_role__c` that is both a likely candidate for exclusion from sync and has a too-long API name.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007x7ERQAY" target="_blank">W-031293</a>

**Comment by tet3** [comment]
Specific to `npsp__related_opportunity_contact_role__c`, and any other future packaged fields - I think it actually needs to be stored without the namespace, or the namespace stripped when actually doing the syncing. But still needs to be fixed with a wider column for the field name.

**Comment by mbeaty-sf** [comment]
Additional Hub Post - https://powerofus.force.com/s/question/0D51E00005Ny3eWSAR/unwelcome-reciprocating-ocrs relating to this issue.

**Comment by mbeaty-sf** [comment]
Just to update this issue, as it also directly relates to the outcome of Related Opportunity Contact Role field copying values over onto reciprocal Relationship records, even when selected to be excluded in the settings.

https://github.com/SalesforceFoundation/NPSP/blob/724274a67f5fbfe3a5b397fe6a03eaeca7b9b7d9/src/classes/STG_PanelRel_CTRL.cls#L108 in STG_PanelRel_CTRL.cls qualifies the API name has to **not include** the npe4_ namespace, in order to be displayed in the list of available fields. The field `npsp__Related_Opportunity_Contact_Role__c` does not have the same namespace, and therefore is included automatically in the "selected" fields when activated.

This means that if this is turned on, the other automatically created reciprocal Relationship copies the Related Opportunity Contact Role value to the reciprocal Relationship record, and if the setting is active, it cannot be selected as a field to be excluded. Selecting it means either an error message as listed in the original bug, or the change is saved, but the field being selected is not respected as exclude.

**Comment by mbeaty-sf** [comment]
W-7783092

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phnVQAQ&title=field_integrity_exception-when-adding-field-whose-api-name-exceeds-38-characters-to-relationship-sync-excluded-fields) in the Trailblazer Community for updates.
