### ISSUE TITLE
Deleted objects not passed to AfterDelete triggers

### ISSUE THREAD

**Issue by garethpdx** [SalesforceFoundation/NPSP#4662]
When deleting a Contact, AfterDelete triggers may be called but Contact details are not provided to the trigger. This seems to be exclusive to AfterDelete. BeforeDelete does gets a list of objects to be deleted.

This can be replicated on a fresh scratch org with NPSP 3.162. Add an apex class that logs the lists provided by the trigger:

```
global with sharing class CON_DataSendGM_TDTM extends npsp.TDTM_Runnable {
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> listNew, List<SObject> listOld, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        if (triggerAction == npsp.TDTM_Runnable.Action.AfterDelete){
            System.Debug('listNew: ' + listNew);
            System.Debug('listOld: ' + listOld.size());
        }
        return null;
    }
}
```

Set up the trigger:
npsp__Class__c: CON_DataSendGM_TDTM
npsp__Object__c: Contact
npsp__Active__c: true
npsp__Asynchronous__c: true
npsp__Load_Order__c: 3
npsp__Trigger_Action__c: AfterDelete
npsp__User_Managed__c: true

Then delete a contact. Per our custom class, listOld should have the Contact that was deleted. Instead the following is logged:
```
12:21:18:200 USER_DEBUG [4]|DEBUG|listNew: null
12:21:18:200 USER_DEBUG [5]|DEBUG|listOld: 0
```
I see that elsewhere NPSP expects deleted objects to be passed along for AfterDelete, for example [CON_ContactMerge_TDTM](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/CON_ContactMerge_TDTM.cls#L66).

Scratch Org Details
NPSP: 3.162
Organization Edition: Developer Edition
Instance: CS22

**Comment by jesslopez-sf** [comment]
Hi @garethpdx,
Just out of curiosity, does your Trigger Handler work when you uncheck the Asynchronous checkbox? The main difference with our CON_ContactMerge_TDTM class is that it runs synchronously, as all of our Trigger Handlers do out of the box.  

I replicated your issue with a custom trigger handler running in the After Delete context asynchronously and I can pinpoint exactly why it's not showing any values in the oldList when it runs via our @future method. (It worked fine when it was not asynchronous).  I just need to determine if that was done by design (and if so, add that to our documentation). If not, I'll write up my findings and pass them to our engineers. Thanks!

**Comment by force2b** [comment]
The current implementation of asynchronous TDTM triggers will actually not work right for the AfterDelete context. Not that it's obvious, but this is actually issue #1795. As it turns out there is a community contribution #4521 to fix this issue that we'll be bringing into one of our upcoming sprints.

**Comment by jesslopez-sf** [comment]
@force2b - I totally missed that contribution. That's great timing. Thanks for jumping in here!

**Comment by coriobriensfdo** [comment]
thank you for submitting @garethpdx! And for reviewing @jesslopez-sf and @force2b! I'll add this to our existing WI.

**Comment by coriobriensfdo** [comment]
**Lurch: Attach W-008581

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gq4AAA" target="_blank">W-008581</a>

**Comment by mbeaty-sf** [comment]
W-7782879

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phXMQAY&title=npsp-tdtm-deleted-objects-not-passed-to-afterdelete-triggers) in the Trailblazer Community for updates.
