### ISSUE TITLE
Multi-Currency Causing Incorrect Campaign Allocations

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4714]
**Issue**
With Multi-Currency enabled, the automatic assignment of GAUs from a Primary Campaign Source on creation of an Opportunity is calculating conversion rates differently than expected. Values differ in the Amount field, Allocation record, and Payment totals.

**Steps to Recreate**

1. Ensure that Multi-Currency is enabled and create another currency in addition to the default
2. Create a General Accounting Unit (GAU)
3. Create a new Campaign with a the GAU you created in step 1 
4. Create an Opportunity with currency CAD (currency other than the default), and Primary Campaign Source as the Campaign you created in previous step

**Result** 
An Opportunity is created with one GAU Allocation to the Campaign automatically; however, references to the total will differ between the Allocation record, Amount field, and Payment records as to the conversion.

**Conversion Settings**
Advanced Currency was enable under Company Information, and set to the following:

![image](https://user-images.githubusercontent.com/53280203/67251900-8b53c100-f425-11e9-9c78-7eff2f119cc4.png)

**Opportunity Creation**
Upon creating a single Opportunity with a value of $1000 CAD, and being attached to a Campaign with a GAU Allocation of 100%, the following was the result:

![image](https://user-images.githubusercontent.com/53280203/67251922-a7576280-f425-11e9-905b-431a7c745d04.png)

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HnlPQAS" target="_blank">W-037009</a>

**Comment by Przemowild** [comment]
Do you have the fix scheduled? Our customer is affected by this bug. When is it going to be resolved? Thanks.

**Comment by dnorman1014** [comment]
Do we have a ETA

**Comment by coriobriensfdo** [comment]
@Przemowild and @dnorman1014 we don't have a fix scheduled just yet, but the team is aware of it. I've let them know you're also affected.

**Comment by RiderM780** [comment]
Hi. Is there any updates regarding this issue? We are having the same problem and it also happens when creating the GAU Allocation manually after creating the opportunity. It also happen with some of the currencies but not all of them.
Appreciate any updates and/or workarounds.

**Comment by coriobriensfdo** [comment]
Hi @RiderM780, not a specific ETA, but I can assure you that the Product Managers and Developers are in active talks about how best to solve this problem. 

I understand that percentage based campaign allocations are having this issue, but that fixed amount are not. Are you able to temporarily use fixed amounts instead of percentage until we can resolve the problem?

**Comment by RiderM780** [comment]
Hi @coriobriensfdo, thanks for your answer. We could created the allocations manually in each donation we receive but I don't think I can set up the campaign with a fixed amount allocation, right? 
I'm not sure if this issue is related but we are now having two GAU allocations being created only in donations with a currency other than USD. One allocation is "0" and the other one has the usual conversion error.
I'll create a case for this issue but thought it will be worthy to mention it here.
Thanks,

**Comment by RiderM780** [comment]
This is great. Thanks. Any recommendation on how to fixed all the opportunities that were creating previous the fixed and have wrong amounts? Thanks.
