### ISSUE TITLE
Recurring Donations: High CPU usage with fixed-length and customizable rollups

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4753]
**Summary**

When creating fixed-length Recurring Donations (open-ended status not Open) with a lot of installments (60 in this case), and customizable rollups are enabled CPU usage increases dramatically. Adding Opportunity Naming Rules also increases the CPU usage, making it difficult for any additional code or process to also run. 

**Workaround**

Create Recurring Donation records with smaller installments, increasing the value slowly to avoid many opportunities needing to be created at once.

**Steps to Repeat**

1. In a fresh scratch org with legacy rollups and no naming rules, edit Recurring Donation custom setting to increase Maximum Donations to **60**.
2. Create a Recurring Donation record for a Contact, Any Amount, Any Installment Period. Set Open-Ended Status to **None** and Installments to **60**.
3. Review debug log: CPU is 1300 out of 10000
4. Enable CRLPs (with no other edits) and create an identical Recurring Donation record.
5. Review debug log: CPU is 3961 out of 10000
6. Create two basic Opportunity Naming Rules and create an identical Recurring Donation record.
7. Review debug log: CPU is 4771 out of 10000

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoCCQA0" target="_blank">W-037275</a>

**Comment by Fred-Triest** [comment]
The workaround for slowly increasing the installments amount is no longer working. Is there anyone working on this or can you provide an ETA for the fix? We are in the middle of a $35 million dollar capital campaign and we aren't able to accommodate donors with over 40 installment amount recurring donations.

**Comment by judisohn** [comment]
Hi @Fred-Triest - as you can see, this fix is being pushed to sandboxes starting tonight (1/8) and production next week. I would love to know if it helps you with this issue. Thanks for your patience.

**Comment by Fred-Triest** [comment]
Hi @judisohn ! Thank you so much for acting on this issue so quickly. This is perfect timing since we are working on a custom object for moves management this month and tying that new object in with Recurring Donations for our capital campaign pledges. Since our Recurring Donations are tied to 3rd party platforms (FormAssembly and iATS Payment Processing) I don't believe I can fully test this in the sandbox this week. I will definitely respond here if it works and based on the new NPSP setting to delay rollups related to Recurring Donations until nightly rollup jobs, I am confident it will.

**Comment by coriobriensfdo** [comment]
Thanks for the response @Fred-Triest. If you do see any issues, can you post in the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) and tag us? Thanks!
