### ISSUE TITLE
Recurring Donation not creating next scheduled donation

### ISSUE THREAD

**Issue by plutusadmin** [SalesforceFoundation/NPSP#5129]
A recurring donation was just created and the first donation was processed and marked closed won.  

The next open ended installment was not created as a pledged opportunity.  

![MissingNewDonation](https://user-images.githubusercontent.com/61158581/74674100-a38edf00-517e-11ea-994f-468ac6b29929.JPG)
![RecurringDonationBug](https://user-images.githubusercontent.com/61158581/74674101-a4277580-517e-11ea-8fda-664e353ab3fd.JPG)

**Comment by jamesbsfdc** [comment]
Hi there, would you mind posting about this in the Power of Us Hub rather than on GitHub as we prefer to answer review posts like this in the Hub first. Posting in the Hub allows us to troubleshoot and validate the issue, and if there is indeed a bug we can then write up a detailed issue. 

https://powerofus.force.com/s/article/SFDO-CS-Reporting-Issues
https://powerofus.force.com/s/article/SFDO-BP-Ask-Questions-in-the-Hub

You should be able to access the Hub using the same login you use to access Salesforce.

Thanks 

James

**Comment by plutusadmin** [comment]
Thanks, James.  I posted my question in the hub.

It appears that 2 others are having the same problem.

[image: Screenshot 2020-02-17 at 9.12.38 PM.png]
