### ISSUE TITLE
Delete All Data in trial org causes Divide by 0 in CRLP

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/NPSP#5370]
I am not involved with this issue, but I noticed this post by a Hub participant stating that Setup > Delete All Data in a trial org caused MathException Divide by 0 errors in customizable rollups:
https://powerofus.force.com/s/question/0D51E00005I7xJm/unable-to-delete-all-data-using-setup-function?s1oid=00D00000000hWLM&s1nid=0DB800000004Fa7&emkind=chatterCommentNotification&s1uid=0058000000DE9g6&emtm=1587575048376&fromEmail=1&s1ext=0

Here's the post detail.  Apparently he had imported only contacts and accounts, no opportunities:

Imported some data improperly (about 500 contact/account records) for a new org and thought it would be easier to just start fresh. However the Delete All Data function launched from Setup only partially removes a small number of data records. On the first run, about 9 account/contact records were removed, and three error messages were sent via email (see below). Decided to run Delete All a second time and after it stopped, about 15 more account/contact records were deleted, but no error messages were in the log. I have no customizations - it's a new trial setup.
Any advice or should I just keep submitting the Delete All request ?

Error #1:
Error Type: System.MathException
Error Date: 2020-04-21 16:04:47
Message: "Divide by 0
Rollups State:"
Context: CRLP
Error #2:
Error Type: Job Error
Error Date: 2020-04-21 16:04:46
Message: "There were one more errors updating or inserting the following records:
* 0013h000008Lc46AAC: ENTITY_IS_DELETED- entity is deleted"
Context: CRLP.AccountHardCredit
Error #3:
Error Type: Job Error
Error Date: 2020-04-21 16:04:46
Message: "There were one more errors updating or inserting the following records:
* 0013h000008Lc2eAAC: ENTITY_IS_DELETED- entity is deleted"
Context: CRLP.AccountHardCredit

**Comment by coriobriensfdo** [comment]
@davidchengIC thank you for taking the time to loop us in, but we only create Issues in GitHub for bugs that can be recreated in clean orgs. At this point we have noticed a few posts in the hub with the same error but in quite different scenarios, and there is no known bug at this point. We're keeping an eye on the situation and testing in our own orgs, and we'll be sure to create an Issue if we find a problem with the NPSP (rather than with Salesforce core for example).

Thanks for being an amazing Community member!!
