### ISSUE TITLE
Opportunity is not getting renamed using NPSP setting when I create opportunity from site user.

### ISSUE THREAD

**Issue by shankish** [SalesforceFoundation/NPSP#5485]
I got following email in my inbox:

---Start of email---

Salesforce encountered these NPSP errors. To learn more about common errors, see "Troubleshoot the Nonprofit Success Pack" on the Power of Us Hub. If you're unsure how to resolve the errors, post a message in the Nonprofit Success Pack group: https://powerofus.force.com/HUB_NPSP_Group

Errors:

----------
 Error #1:

Error Type: System.NullPointerException
Error Date: 2020-05-18 09:47:13
Message: "Attempt to de-reference a null object"
Context: OPP

Stack Trace:
 Stacktrace available at the time of saving the record - (npsp)

---End of email---

When I remove the auto-naming setting from NPSP setting, I did not receive this error. I tried with 2-3 combinations of auto-naming but nothing worked.

**Comment by jamesbsfdc** [comment]
Hi @shankish 
Unfortunately we don't provide support via GitHub issues. Would you mind posting this in the Power of Us Hub? We can reply to your post there and direct you to relevant resources.

If you are working with a nonprofit or educational institution you can login to the Power of Us Hub with your production login. Let me know if you do not have access.

**Comment by shankish** [comment]
Hi @jamesbsfdc ,
Thank you replying.
Currently I am developing an add on package for NPSP using my developer org credentials. 
Is there a way for me to log issue without prod credentials?

**Comment by jamesbsfdc** [comment]
Hi @shankish 

It may be possible for you to get access to the Hub with a developer account login. I'm just waiting for a reply from a colleague on this. 

On the specific issue you are experiencing, we have not received any other reports of this issue so as far as we are aware at the moment this is not an issue with NPSP. We do see this error when other code is interacting with ours and it is not using TDTM or for other related issues. I believe one partner may be experiencing a similar error because the update of the opp is happening in a guest user context. Let me come back to you on Hub access

**Comment by jamesbsfdc** [comment]
Hi @shankish 
In order to get access to the Hub:
*Please provide the following information to community@salesforce.org

* First name, last name
* Email
* Dev Org ID, you can find this here (https://help.salesforce.com/articleView?id=000325251&type=1&mode=1)
* Website, this can be a LinkedIn (https://www.linkedin.com/) profile URL

Your Account Name will be “Individual” (how this will appear in the Hub).

**Comment by shankish** [comment]
Hi @jamesbsfdc 

I have sent the required information.

**Comment by shankish** [comment]
Hi @jamesbsfdc,

I had sent an email as request but I haven't received an reply. Is there any update for me?

**Comment by jamesbsfdc** [comment]
Hi Shankish 

Apologies for the delay but this had to be approved. There were concerns from the team that manage Hub as they wanted to validate your interest in the nonprofit community, as your LinkedIn profile was not up to date. 

Can you confirm what this extension package is for and how it is benefiting the nonprofit community and your current role e.g is this something you are working on personally or in a professional capacity - can you email the above to community@salesforce.org?

**Comment by jamesbsfdc** [comment]
Hi again Shankish, spoke to the team involved. They are going to hopefully set up an account for you today

**Comment by shankish** [comment]
Hi @jamesbsfdc 
My hub account is activated now. I have posted the question,

https://powerofus.force.com/s/feed/0D51E00005K5Y6SSAV

Thank you.
