### ISSUE TITLE
Primary Contact Change on Opportunity Does Not Trigger Rollup

### ISSUE THREAD

**Issue by MenachemShanowitz** [SalesforceFoundation/NPSP#5561]
When the primary contact is changed on the Opportunity, if the **only** field changed is Primary Contact it will not refresh the various Rollup Fields on the Contact to include this Opportunity. 

If you were to then refresh the Rollups fields another way, the Contact rollup fields will reflect the Opportunity (because changing the Primary Contact creates Contact Roles).

**Comment by coriobriensfdo** [comment]
We've tested with CRLP and can verify it's happening so we will leave this Issue open. 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbRcQAI" target="_blank">W-042026</a>

**Comment by coriobriensfdo** [comment]
@MenachemShanowitz we tested a few different scenarios again and agree that it's not an issue in Customizable Rollups. We may have had some cache issues in our first round which made it look like the issue was happening for the new code engine. So the good news is that if you upgrade, you'll avoid this problem.
