### ISSUE TITLE
Gift Entry - Create Template "Add New Section" Obscured by Inability to Scroll Page

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6097]
**Issue**
When attempting to create a new template for Gift Entry, if a user is trying to add a new section to the template page, they cannot do so without having to expand the Form Fields sections, or zooming out of the page.

![2020-12-04_15-27-51 (1)](https://user-images.githubusercontent.com/53280203/101225149-9081c880-3645-11eb-8e68-f20282161c26.gif)

<br>
<br>

**Steps to Recreate** 
1. Navigate to Gift Entry and click on the Templates Sub-Tab
2. Click on "Create Template" button
3. Click on the Form Fields Tab
4. Attempt to scroll to the bottom of the "Configure Form Fields" section
a.  Notice that you are unable to access the "Add Section" button at the bottom of the page as it is obscured by the "Next: Batch Settings" Footer
5. Open a section in the left-hand pane's "Form Fields" section and notice that scrolling will now allow you to go further and access the "Add Section" button at the bottom of the page

**Workaround**
Expanding the Form Fields section from the left pane of Gift Entry will further allow the user to scroll and access the Add Section button. User can also use the browser's zoom functionality to zoom out and access this button.

**Comment by jesslopez-sf** [comment]
W-8538306

**Comment by jamesbsfdc** [comment]
### Additional Workaround

If the workarounds detailed above do not work it this may be due to the volume of fields in your Gift Entry form. 

Two potential additional options:
- 1. Remove some fields from the form such that the length of the form does not exceed the length of the left hand section when all fields are expanded. This should result in the Add Section button becoming visible again. Add a new section or sections and re-add any removed fields
- 2. Recreate the form from scratch and add the form sections before you add the fields

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRxQAI&title=gift-entry-create-template-add-new-section-obscured-by-inability-to-scroll-page

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
