### ISSUE TITLE
Checkbox picklist values marked as checked in BGE table when value is false

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6126]
If a picklist with true/false values has been mapped to a checkbox on the target object (per https://powerofus.force.com/s/article/NPSP-BGE-Add-Cust-Fields#topic-2649), and a gift is saved in a batch with a 'False' value on the picklist, the BGE table still shows the value as "true" with a checkbox.

![image](https://user-images.githubusercontent.com/55844773/102366154-4faf7b00-3f86-11eb-9c28-b4979624acaf.png)

**Steps to Reproduce:**

1. Create a picklist on the Data Import object with the values 'True' and 'False'.
2. Create a checkbox on the target object.
3. In Advanced Mapping, map the picklist from the DI object to the checkbox on the target object.
4. Navigate to the Gift Entry app.
5. Create a new template and add the new picklist to the form. Add the checkbox picklist field to the batch table columns. Save the template.
6. Create a new batch with the new template.
7. Create a new gift with the checkbox picklist value set to 'False' and save it.
8. In the batch table, the gift will have the value of "true" (checked) in the table.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008l6KWIAY/view

**Comment by SaraStuart** [comment]
We are experiencing the same issue and would appreciate a quick turn around on this as the end of the year and staff holidays are fast approaching.

**Comment by geoffhom** [comment]
We are experiencing the same problem. FYI, this occurs with Opportunity's "Is Gift Aid Excluded" field. If you add that to the default template and then try to make a new batch, it's the same problem. (There's an additional bug where it won't even save if that field is unchecked. You have to check and then uncheck it. But it displays in the table as checked. Will file a separate bug report on the saving error.)

It seems things were fine on December 15 and then not working on December 17. 

<img width="326" alt="Screen Shot 2020-12-22 at 7 41 47 AM" src="https://user-images.githubusercontent.com/21103/102895109-bf5fb300-4429-11eb-8b26-7917e1e64837.png">

<img width="265" alt="Screen Shot 2020-12-22 at 7 44 30 AM" src="https://user-images.githubusercontent.com/21103/102895012-950df580-4429-11eb-9082-167b36bdb89a.png">

**Comment by judisohn** [comment]
@geoffhom @SaraStuart This issue has not been picked up yet to be worked on. Please feel free to open a support case and reference this Issue so it can be attached. Unfortunately, we are not releasing a new version of NPSP until early 2021 and we don't provide direct support in Github. Thanks!

**Comment by geoffhom** [comment]
@judisohn: thank you for the info! @SaraStuart: my org has good support (I think it's the top), so I'll look into opening a support case.

**Comment by SaraStuart** [comment]
@judisohn  Thank you!  @geoffhom  Thank you for opening the ticket.  I'm new to Salesforce administration, do you think I should also open a ticket or should I wait and hear an update from you?

**Comment by geoffhom** [comment]
Hi @SaraStuart! Sorry for not updating! I'm new to Salesforce, too. My org (Mercy Ships) pays for the top support (Premier+), so my understanding is we can submit as many cases as needed; we don't pay per case. (I am used to Apple Development, where you do pay per instance.) I'm not sure how the other Salesforce plans work. 

Anyway, Salesforce Support got back to me within a day. They noted that the issue with the checkboxes in the table is supposed to be fixed in the next release. That's scheduled to deploy to all sandboxes on January 6, and then to production the week after. 

My org has a second issue, noted above, that any checkbox (even ones native to NPSP, which I did verify later) reports an error and prevents saving in batch entry. Salesforce Support suggested waiting until the release on January 6 to see if that fixes it. I asked if there was a way to check the beta earlier, but they said no. 

If you have any more questions, let me know. This was my first case, and they did get back to me promptly, so that was good. I encourage you to try it out next time you have an issue.

**Comment by SaraStuart** [comment]
Hi @geoffhom  Thanks for the update!  It is much appreciated!  I am just getting set up with Premier support but at the basic level and your reporting of your experience with Salesforce Support is encouraging.

**Comment by mbeaty-sf** [comment]
For context, I believe that the issue @geoffhom is referring to as the second issue is this https://github.com/SalesforceFoundation/NPSP/issues/5890

**Comment by geoffhom** [comment]
@mbeaty-sf: Thank you for the link. The "second issue" (and most important to us) is the one I linked above #6138. But you're kinda right that #5890 is the issue that should definitely be fixed in this week's NPSP version released to sandboxes.

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRdQAI&title=gift-entry-checkbox-picklist-values-marked-as-checked-in-the-ge-table-when-value-is-false

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
