### ISSUE TITLE
Gift Entry- Donation Allocation Bundle assigns to Default GAU even when manually changed to a different GAU, and allocation calculations for the first row won't go to 0 if the first row is left alone

### ISSUE THREAD

**Issue by nicklyndonprolocity** [SalesforceFoundation/NPSP#6134]
On multiple organization's instances, I am experiencing that when an Allocation Bundle is used in the New Gift Entry form and a default GAU exists, when the first row is changed to another GAU besides the default GAU, the eventual Opportunity still has the default GAU for the GAU Allocation. So to work around this, we are leaving the first row alone and adding additional rows for the desired GAU's to be used. However, the calculations won't allow the first row to automatically = $0. It can be any other number, positive or negative, but it cannot equal $0, which is what we want because we want $0 to go towards the default GAU. So when entering a gift for $100, we leave the first row alone, and then add a row for $50 to one GAU, and then add a row and start typing in 50 for another GAU. It starts to calculate the first row from $50 to $45 as you enter the "5". But then you enter the "0" and the calculations stop, and you are left with 3 rows, one with $45, and two with $50. Either the first row should reflect the changed GAU or the calculations should allow you to "0" out the first row and the automatic calculation should do that.

**Comment by mbeaty-sf** [comment]
Hi @nicklyndonprolocity, 

We don't troubleshoot issues like this on Github so I will need to close the issue here; could you please post your issues with any supporting screenshots, etc. on the Power of Us Hub? There is a Gift Entry Group here - https://powerofus.force.com/s/group/0F91E000000bs7KSAQ/gift-entry

There are a few existing Issues involving GAUs with Gift Entry, and I want to chat further to see if it falls in with one of these:

1. https://github.com/SalesforceFoundation/NPSP/issues/5955
2. https://github.com/SalesforceFoundation/NPSP/issues/5824
3. https://github.com/SalesforceFoundation/NPSP/issues/5699
