### ISSUE TITLE
Cannot Send Email Acknowledgement via Workflow Rule if User Language is not English

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6185]
**Issue**
If a User record's Language is set to anything other than English, using the Email Acknowledgement (https://powerofus.force.com/s/article/NPSP-Send-Email-Acknowledgments), does not work and will not complete, resulting in error.

**Steps to Recreate**
1. Navigate to Setup > Workflow Actions > Workflow Rules > and activate the **Opportunity Email Acknowledgment** Workflow Rule
2. Create a User record and select Locale Settings > Language > and select anything other than English
3. Create a Closed/Won Donation Opportunity on a Contact record in the org
4. Login as the User record created in step 2
5. Navigate to the Opportunities Tab
6. Click the drop-down menu and select "To Be Acknowledged"
7. Select the Opportunity created in step 3, and then click right-most corner button of the List View
8. Notice the Error:

![2021-01-15_16-10-21 (1)](https://user-images.githubusercontent.com/53280203/104790554-5e877a00-574c-11eb-895f-e6eb753b6777.gif)

<br>
<br>

**Workaround**
Users cannot edit the Workflow because it is managed.

**Comment by mbeaty-sf** [comment]
W-8732098

**Comment by jamesbsfdc** [comment]
### Workaround

The criteria for the workflow rule checks the value of the npsp__Acknowledgment_Status__c field matches the values defined in the  npsp__sendacknowledgmentfirestatus Custom Label. Because of this bug the values are not being passed to the workflow correctly. 

Where the user's language is one of the translated languages in NPSP, the user will need to override the translated value for the Custom Label

Navigate to: 

- Setup --> Custom Labels --> sendAcknowledgmentFireStatus

Under the Packaged Translations section:

- Select Override next to the relevant language (e.g Spanish, German etc)
- Enter "Email Acknowledgment Now" in Translation Text and click Save

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kOdQAI&title=users-cannot-acknowledge-donations-by-email-if-their-language-is-one-of-the-languages-translated-by-npsp

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
